config/routes.rb
Rails.application.routes.draw do

  resources :villains
  root 'superheros#index'
  get 'superheros/', to: 'superheros#index', as: :index_superheros
  get 'superheros/new', to: 'superheros#new', as: :superhero_new
  post 'superheros', to: 'superheros#create'
  get 'superheros/:id/edit', to: 'superheros#edit', as: :edit_superhero
  patch 'superheros/:id', to: 'superheros#update'
  get 'superheros/:id', to: 'superheros#show', as: :superhero
  delete 'superheros/:id', to: 'superheros#destroy'

end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
  validates :name, :secret_identity, :image_url, presence: true
  has_many :villains
end

app/models/villain.rb
class Villain < ActiveRecord::Base
  belongs_to :superhero
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/superheroes_controller.rb
class SuperherosController < ApplicationController

  def indexx
    @superhero = Superhero.all
  end

  def create
    superhero.create(superhero_params)
    redirect_to '/superheros'
  end

  def new
    @superhero = superhero.new
  end

  def edit
    @superhero = superhero.find(params[:id])
  end

  def update
    @superhero = superhero.find(params[:id])
    @superhero.update_attributes(superhero_params)
    redirect_to 'index_superheros_path'
  end

  def show
    @superhero = superhero.find(params[:id])
  end

  def destroy
    @superhero = superhero.find(params[:id])
    @superhero.destroy
    redirect_to 'index_superheros_path'
  end

  private

  def superhero_params
    params.require(:superhero).permit(:name, :powers, :secret_identity, :nemesis, :villains_captured, :image_url)
  end
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController

  before_action :load_superhero, only: [:show, :update, :destroy, :edit]

  def index
    @superhero = Superhero.all
  end

  def create
    Superhero.create(superhero_params)
    redirect_to superheros_path
  end

  def new
    @superhero = Superhero.new
  end

  def edit
  end

  def update
    @superhero.update_attributes(superhero_params)
    redirect_to superheros_path
  end

  def show
  end

  def destroy
    @superhero.destroy
    redirect_to superheros_path
  end

  private

  def load_superhero
    @superhero = Superhero.find(params[:id])
  end

  def superhero_params
    params.require(:superhero).permit(:name, :powers, :secret_identity, :nemesis, :villains_captured, :image_url, :alliance)
  end
end

app/controllers/villains_controller.rb
class VillainsController < ApplicationController
  before_action :set_villain, only: [:show, :edit, :update, :destroy]

  # GET /villains
  # GET /villains.json
  def index
    @villains = Villain.all
  end

  # GET /villains/1
  # GET /villains/1.json
  def show
  end

  # GET /villains/new
  def new
    @villain = Villain.new
  end

  # GET /villains/1/edit
  def edit
  end

  # POST /villains
  # POST /villains.json
  def create
    @villain = Villain.new(villain_params)

    respond_to do |format|
      if @villain.save
        format.html { redirect_to @villain, notice: 'Villain was successfully created.' }
        format.json { render :show, status: :created, location: @villain }
      else
        format.html { render :new }
        format.json { render json: @villain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villains/1
  # PATCH/PUT /villains/1.json
  def update
    respond_to do |format|
      if @villain.update(villain_params)
        format.html { redirect_to @villain, notice: 'Villain was successfully updated.' }
        format.json { render :show, status: :ok, location: @villain }
      else
        format.html { render :edit }
        format.json { render json: @villain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villains/1
  # DELETE /villains/1.json
  def destroy
    @villain.destroy
    respond_to do |format|
      format.html { redirect_to villains_url, notice: 'Villain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_villain
      @villain = Villain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def villain_params
      params.require(:villain).permit(:name, :arch_nemesis, :powers, :evil_plan, :superhero_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheroes_helper.rb
module SuperheroesHelper
end

app/helpers/villains_helper.rb
module VillainsHelper
end

app/views/layouts/_navbar.html.erb
<nav id="my-nav-bar" class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
       <%= link_to image_tag("logo.png"), superheros_path %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="page">
    <%= yield %>
  </div>

</body>
</html>

app/views/superheros/_form.html.erb
<%= form_for @superhero do |sup| %>
  <p>
    <%= sup.label :name %><br>
    <%= sup.text_field :name %>
  </p>

  <p>
    <%= sup.label :powers %><br>
    <%= sup.text_field :powers %>
  </p>

  <p>
    <%= sup.label :secret_identity %><br>
    <%= sup.text_field :secret_identity %>
  </p>

  <p>
    <%= sup.label :nemesis %><br>
    <%= sup.text_field :nemesis %>
  </p>

  <p>
    <%= sup.label :villains_captured %><br>
    <%= sup.number_field :villains_captured %>
  </p>

  <p>
    <%= sup.label :image_url %><br>
    <%= sup.text_field :image_url %>
  </p>

  <p>
    <%= sup.label :alliance %><br>
    <%= sup.text_field :alliance %>
  </p>

  <p>
    <%= sup.submit %>
  </p>
<% end %>

app/views/superheros/edit.html.erb
Edit superhero:

<%= render 'form' %>

<%= button_to "Back to index", index_superheros_path, method: :get %>

app/views/superheros/index.html.erb
<div class="superhero_list">
The mighty... <%=button_to "Add new Superhero!", superhero_new_path, method: :get %>
<br>


<% @superhero.each do |sup| %>
<%= image_tag sup.image_url, :class => 'images' %> <br>
<%= link_to sup.name, superhero_path(sup)%> <br>
<br>
<% end %>
</div>

app/views/superheros/new.html.erb
Add a New superhero:

<%= render 'form' %>

<%= button_to "Back to index", index_superheros_path, method: :get %>

app/views/superheros/show.html.erb
<div class="superhero"><%= image_tag @superhero.image_url, :class => 'images_show' %> <br>
NAME: <%= @superhero.name %> <br>
POWERS: <%= @superhero.powers %> <br>
SECRET IDENTITY: <%= @superhero.secret_identity %> <br>
NEMESIS: <%= @superhero.nemesis %> <br>
VILLAINS CAPTURED: <%=@superhero.villains_captured %> <br>
Alliances: <%=@superhero.alliance %> <br>


superhero_ID#: <%= @superhero.id %> <br>
superhero_OBJECT_ID: <%= @superhero_object_id %> <br>


<%= button_to "Back to index", index_superheros_path, method: :get %>
<%= button_to "Edit this superhero", edit_superhero_path(@superhero), method: :get %>
<%= button_to "Delete this superhero!", @superhero, method: :delete, data: {
  confirm: "Are you sure you want to continue?  Confirming will permanently remove superhero from the database!"
  } %>
</div>

app/views/villains/_form.html.erb
<%= form_for(@villain) do |f| %>
  <% if @villain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@villain.errors.count, "error") %> prohibited this villain from being saved:</h2>

      <ul>
      <% @villain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :arch_nemesis %><br>
    <%= f.text_field :arch_nemesis %>
  </div>
  <div class="field">
    <%= f.label :powers %><br>
    <%= f.text_field :powers %>
  </div>
  <div class="field">
    <%= f.label :evil_plan %><br>
    <%= f.text_field :evil_plan %>
  </div>
  <div class="field">
    <%= f.label :superhero_id %><br>
    <%= f.text_field :superhero_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/villains/edit.html.erb
<h1>Editing Villain</h1>

<%= render 'form' %>

<%= link_to 'Show', @villain %> |
<%= link_to 'Back', villains_path %>

app/views/villains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Villains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Arch nemesis</th>
      <th>Powers</th>
      <th>Evil plan</th>
      <th>Superhero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @villains.each do |villain| %>
      <tr>
        <td><%= villain.name %></td>
        <td><%= villain.arch_nemesis %></td>
        <td><%= villain.powers %></td>
        <td><%= villain.evil_plan %></td>
        <td><%= villain.superhero %></td>
        <td><%= link_to 'Show', villain %></td>
        <td><%= link_to 'Edit', edit_villain_path(villain) %></td>
        <td><%= link_to 'Destroy', villain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Villain', new_villain_path %>

app/views/villains/new.html.erb
<h1>New Villain</h1>

<%= render 'form' %>

<%= link_to 'Back', villains_path %>

app/views/villains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @villain.name %>
</p>

<p>
  <strong>Arch nemesis:</strong>
  <%= @villain.arch_nemesis %>
</p>

<p>
  <strong>Powers:</strong>
  <%= @villain.powers %>
</p>

<p>
  <strong>Evil plan:</strong>
  <%= @villain.evil_plan %>
</p>

<p>
  <strong>Superhero:</strong>
  <%= @villain.superhero %>
</p>

<%= link_to 'Edit', edit_villain_path(@villain) %> |
<%= link_to 'Back', villains_path %>